spring:
  profiles:
    active: local
server:
  port: 8080
---
spring:
  profiles:
    - local
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9093
        - localhost:9094
      key-deserializer:
      value-deserializer:
      group-id: library-events-group


---
spring:
  profiles:
    - nonprod
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9093
        - localhost:9094
      key-deserializer:
      value-deserializer:
      group-id: library-events-group

---
spring:
  profiles:
    - prod
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9093
        - localhost:9094
      key-deserializer:
      value-deserializer:
      group-id: library-events-group
